25 finish the backend project business layer code 2
RunpengNie/underdog-s-struggling pull request #36
Opened 2024-07-20 23:26 UTC by TonyLiu836

Implemented the following:
 - display all entries (reference mode)
 - get entries by tag(s)
 - get entries by topics

Have some questions about search by tag/title/subtitle. Maybe I'm missing something but how is "search by tag/title/subtitle" different to "get entries by topic/tag"?

2024-07-22 18:20 UTC, RunpengNie commented
According to the issue page: https://github.com/RunpengNie/underdog-s-struggling/issues/8, search and get are basically same thing. I think we tend to use search rather than get to describe this functionality, which means we should use search in the doc controller. 

Please resolve the conflicts and mark the PR is ready so that I can review it. 

Let me know if you have more questions, or maybe we can have a short meeting to discuss.

2024-07-28 00:07 UTC, TonyLiu836 commented
After further discussion, will consider search and get to mean the same for now. 

"Search by tag/title/subtitle" and "Display [Topic] page (topic is a parameter) + Display by [Tag] (tag is a parameter)" are redundant.

2024-08-04 20:28 UTC, RunpengNie requested changes
Please also remember to remove the `.idea` folder in your PR. Check to see if .gitignore is still working.

2024-08-04 20:28 UTC, RunpengNie commented on Backend/Underdogs-Struggling/src/main/java/com/TheTroisMousquetaires/Underdogs/Struggling/service/impl/EntryServiceImpl.java
> +
Why do we have 2 empty functions here? Please comment with a TO DO sign if they are intentionally left blank.

2024-08-04 20:28 UTC, RunpengNie commented on Backend/Underdogs-Struggling/src/main/java/com/TheTroisMousquetaires/Underdogs/Struggling/entity/Tag.java
> +    private List<Entry> entries;
Why change it to a list? We should not have duplicate tags.

2024-08-04 20:28 UTC, RunpengNie commented on Backend/Underdogs-Struggling/src/main/java/com/TheTroisMousquetaires/Underdogs/Struggling/entity/Entry.java
> +    }
Interesting, Why don't we just return `tags`?

2024-08-04 20:28 UTC, RunpengNie commented on Backend/Underdogs-Struggling/src/main/java/com/TheTroisMousquetaires/Underdogs/Struggling/dao/EntryRepository.java
> +    List<Entry> findEntriesByTags(@Param("tags") Set<Tag> tags, @Param("tagCount") long tagCount);
This one probably will not work. We do not store `tag` information in `Entries` table, entry-tag records are stored in the `EntryTags` table.

2024-08-04 20:28 UTC, RunpengNie commented on Backend/Underdogs-Struggling/src/main/java/com/TheTroisMousquetaires/Underdogs/Struggling/controller/DocServiceController.java
> +//    @Autowired
If we do not need this annotation we can remove this comment.

2024-08-18 18:16 UTC, RunpengNie commented on .idea/.gitignore
`.idea` folder still exists in code change, I believe you need to delete it locally and then commit. Otherwise gitignore won't work.

2024-08-18 18:17 UTC, RunpengNie commented on Backend/Underdogs-Struggling/src/main/java/com/TheTroisMousquetaires/Underdogs/Struggling/dao/EntryRepository.java
> +//    @Query("SELECT e FROM Entry e JOIN e.tags t WHERE t IN :tags GROUP BY e HAVING COUNT(DISTINCT t) = :tagCount")
If we do not need this comment we can remove it.

2024-08-18 18:17 UTC, RunpengNie commented on Backend/Underdogs-Struggling/src/main/java/com/TheTroisMousquetaires/Underdogs/Struggling/entity/Entry.java
> +//    private Set<Tag> tags = new HashSet<>();
Remove?

2024-08-18 18:19 UTC, RunpengNie commented on Backend/Underdogs-Struggling/src/main/java/com/TheTroisMousquetaires/Underdogs/Struggling/entity/Tag.java
> +    Set <Entry> entries;
I think `Set<Type>` is the convention.

2024-08-18 18:20 UTC, RunpengNie commented on Backend/Underdogs-Struggling/src/main/java/com/TheTroisMousquetaires/Underdogs/Struggling/service/impl/EntryServiceImpl.java
> +        // Convert Set<Tag> to List<Long> for tag IDs
Supper minor, I believe: 
```java
// return entryRepository.findEntriesByTags(tags);
// Convert Set<Tag> to List<Long> for tag IDs
``` 
will be better

2024-08-18 18:25 UTC, RunpengNie approved these changes
LGTM! 
I like the JPA you write, it looks good. 
All the changes that need to be made have nothing to do with program logic, but are related to code standards. You can merge the PR directly after making the changes.

2024-08-20 03:01 UTC, merged